# Author - Shadman Shariar

**Topic - Numpy**

In [4]:
import numpy as np

In [5]:
arr = np.array([[1,2,3,4,5]], np.int64)

In [6]:
arr[0,1]

2

In [8]:
arr.dtype

dtype('int64')

In [10]:
flag = np.array([[1,2,3],[6,7,8],[5,6,9]])

In [11]:
flag

array([[1, 2, 3],
       [6, 7, 8],
       [5, 6, 9]])

In [12]:
flag.size

9

In [13]:
flag.shape

(3, 3)

**Fill Array**

In [15]:
fill = np.zeros((2,4))

In [16]:
fill

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
range = np.arange(12)
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
distribute = np.linspace(1,5,5)
distribute

array([1., 2., 3., 4., 5.])

In [21]:
brr = [[1,2,3],[2,3,4],[2,4,6]]
x = np.array(brr)
x

array([[1, 2, 3],
       [2, 3, 4],
       [2, 4, 6]])

In [23]:
x.sum(axis=0)


array([ 5,  9, 13])

In [24]:
x.T

array([[1, 2, 2],
       [2, 3, 4],
       [3, 4, 6]])

In [27]:
ok  = np.array([11,2,3,4,5])
ok.argmax()

0

In [28]:
ok.argmin()


1

In [29]:
ok.sort()

In [30]:
ok

array([ 2,  3,  4,  5, 11])

In [32]:
ok+ok

array([ 4,  6,  8, 10, 22])